{
 "title": "file cont",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Num. of Missing & Delayed files last 15 min",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"vm_metrics\")\n  |> range(start: -15m)  // last update \n  |> filter(fn: (r) => r._measurement == \"file_status\")\n  |> filter(fn: (r) => r.status == \"late\" or r.status == \"missing\")\n  |> group()                                // combine all files\n  |> count(column: \"_value\")                // count number of delayed/missing files\n"
    }
   ]
  },
  {
   "title": "delays/missing over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"vm_metrics\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._measurement == \"file_status\")\n  |> filter(fn: (r) => r.status == \"late\" or r.status == \"missing\")\n  |> group(columns: [\"file_name\"])             // Each file separately\n  |> aggregateWindow(every: 1d, fn: count, createEmpty: false)\n  |> keep(columns: [\"_time\", \"file_name\", \"_value\"])\n\n"
    }
   ]
  },
  {
   "title": "table ",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"vm_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"file_status\")\n  |> group()  \n  |> filter(fn: (r) => r._field == \"size_bytes\")  \n  |> map(fn: (r) => ({\n    source: r.source,\n    file_name: r.file_name,\n    expected_time: r.expected_time,\n    last_modified: r.last_modified,\n    status: r.status,\n    size_bytes: r._value,\n    _time: r._time\n  }))\n  "
    }
   ]
  },
  {
   "title": "file content",
   "type": "gauge",
   "description": "the number of rows in each file",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"vm_metrics\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"file_content_check\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rows\")   // only numeric values\n  |> keep(columns: [\"_time\", \"_value\", \"file_name\"])\n\n"
    }
   ]
  }
 ]
}